### ISSUE TITLE
Average RGB value

### ISSUE THREAD

**Issue by mykolapuliaiev** [gordinmitya/yuv2buf#2]
Hello,
Is it possible to calculate average RGB values of the image before it's converted to Bitmap?
I've tried it with whole resulting bitmap, but it so huge and FPS drops to 7 in average. Also, I've tried it with downscaled bitmap, but it also slow on some phones. Is there a better way to solve this?

Btw, I love your yuv to rgb conversion algorithm! Thank you!

**Comment by gordinmitya** [comment]
Oh no, I missed notification and opened repo only now. Really sorry for that.
In case someone came here with similar question I would recommend:
first take look at [Palette](https://developer.android.com/develop/ui/views/graphics/palette-colors)
if it doesn't fit and you really need exact average – go to opencv and cpp code
