### ISSUE TITLE
Trying to understand padding issues

### ISSUE THREAD

**Issue by acoutts** [gordinmitya/yuv2buf#3]
Hi. On some android devices I’ve observed that there is some padding added. The row stride is > the image width on all 3 planes (YUV420).

Through trial and error I found I only need to trim the padding from the luma channel but not the chroma channels. Coincidentally the pixel stride is 1 on the luma channel and 2 on the chroma channels.

I’m trying to understand why the padding sometimes exists and why it can only be trimmed when pixel stride is 1. 

In my example I observed the following on some devices when streaming YUV420 from camera2:
Image width: 1280
Image height: 720
Y pixel stride: 1
Y row stride: 1536
U pixel stride: 2
U row stride: 1536
V pixel stride: 2
V row stride: 1536

**Comment by gordinmitya** [comment]
Hello @acoutts, just added [a test case](https://github.com/gordinmitya/yuv2buf/blob/master/yuv2buf/src/test/java/ru/gordinmitya/yuv2buf/YuvCommon.java#L30) with your numbers and I looks like code handles them correctly. 

Could you check that's is different on your device vs test case above? And also what is exact issues you faced (crash, wrong picture, smth else)?

**Comment by acoutts** [comment]
Sorry I should clarify the code works great! I just want to better understand why the row stride can sometimes differ and why padding may or may not be present.

**Comment by gordinmitya** [comment]
usually stride may appear when we take crop of the image, so must be 1280x720 is not "native" resolution for camera on your device, so it captures more pixels and just returns you central crop.
in this case rowStride includes "padding" to skip these extra pixels and get to the next row of crop:

![IMG_34CA8A7FB8A3-1](https://user-images.githubusercontent.com/9286092/212487541-a6d439c1-5f70-4bc5-ab0f-eb7cc822559f.jpeg)
1024 took just for example, we can't derive actual height from these parameters

so in case if native resolution of camera matches with requested resolution – there won't be any padding. Hope this helps you understand. For more examples you can google how Mat cropping is implemented in OpenCV
